
def public_pods

source 'https://github.com/CocoaPods/Specs.git' # 公有源

end

def njspec_pods
source 'https://github.com/NJHu/NJSpecs.git' # NJ 私有源

pod 'DYLiveRoom', :path => '../'
end


platform :ios, '10.3'
use_frameworks!

target 'DYLiveRoom_Example' do
inhibit_all_warnings!

njspec_pods

public_pods

target 'DYLiveRoom_Tests' do
inherit! :search_paths


end
end
